apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 7Gi
  hostPath:
    path: "/mnt/data"
  accessModes:
    - ReadWriteOnce